name: flutter_messenger_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_storage: ^11.0.3
  firebase_database: ^10.0.3
  flutter_svg: ^1.1.0
  provider: ^6.0.3
  get_it: ^7.2.0
  phone_number: ^0.12.0+2
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  path: ^1.8.1
  bottom_navy_bar: ^6.0.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_gen: 4.3.0
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/json/

 
  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish.ttf
        
    - family: Lato
      fonts:
        - asset: fonts/Lato.ttf
 
flutter_gen:
  output: lib/generated/assets/
  line_length: 80

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true